### ISSUE TITLE
Crash trying to process Jpeg2000

### ISSUE THREAD

**Issue by 96NekoRS** [xemle/home-gallery#139]
```
C:\Users\mariu\AppData\Local\Temp\caxa\home-gallery\1.15.0\home-gallery\node_modules\exiftool-vendored\dist\ExifToolTask.js:54
            throw new Error(buf.toString());
            ^

Error: Can't locate Image/ExifTool/Jpeg2000.pm in @INC (you may need to install the Image::ExifTool::Jpeg2000 module) (@INC contains: C:\Users\mariu\AppData\Local\Temp\caxa\home-gallery\1.15.0\home-gallery\node_modules\exiftool-vendored.exe\bin\exiftool_files/lib C:/Users/mariu/AppData/Local/Temp/caxa/home-gallery/1.15.0/home-gallery/node_modules/exiftool-vendored.exe/bin/exiftool_files/lib) at (eval 15) line 1.
Can't find table Image::ExifTool::Jpeg2000::Main

    at ReadTask.onStderr (C:\Users\mariu\AppData\Local\Temp\caxa\home-gallery\1.15.0\home-gallery\node_modules\exiftool-vendored\dist\ExifToolTask.js:54:19)
    at BatchProcess._BatchProcess_onStderr (C:\Users\mariu\AppData\Local\Temp\caxa\home-gallery\1.15.0\home-gallery\node_modules\batch-cluster\dist\BatchProcess.js:458:14)
    at Socket.<anonymous> (C:\Users\mariu\AppData\Local\Temp\caxa\home-gallery\1.15.0\home-gallery\node_modules\batch-cluster\dist\BatchProcess.js:96:123)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v20.9.0
Error: [object Object]
```

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
