### ISSUE TITLE
Update import

### ISSUE THREAD

**Issue by mirozv** [xemle/home-gallery#16]
stream.pipe Processed read directories 7 (+7)
stream.pipe Processed map to media 972 (+972)
stream.pipe Processed read directories 18 (+11)
stream.pipe Processed map to media 4014 (+3042)
stream.pipe Processed read directories 31 (+13)
stream.pipe Processed map to media 16515 (+12501)
/app/packages/database/dist/map-media.js:247
      if (geoReverse.address[key]) {
                            ^

TypeError: Cannot read property 'country' of undefined
    at /app/packages/database/dist/map-media.js:247:29
    at Array.forEach (<anonymous>)
    at DestroyableTransform._transform (/app/packages/database/dist/map-media.js:246:59)
    at DestroyableTransform.Transform._read (/app/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (/app/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DestroyableTransform.Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DestroyableTransform.ondata (/app/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at DestroyableTransform.emit (events.js:400:28)
Error: 1

**Comment by mirozv** [comment]
I identified two files. If you want, I can send you Exif data  ?

**Comment by xemle** [comment]
Cool!

Yes, these information would be awesome. I guess the section of geo data with longitude and latitude should be enough.

**Comment by mirozv** [comment]
[77c7118381171000346106ffad005f5596fc-exifToolData.txt](https://github.com/xemle/home-gallery/files/7075185/77c7118381171000346106ffad005f5596fc-exifToolData.txt)
[9a507f28f6ab94252ee40bca662ba203193f-exifToolData.txt](https://github.com/xemle/home-gallery/files/7075186/9a507f28f6ab94252ee40bca662ba203193f-exifToolData.txt)

**Comment by xemle** [comment]
Thank you very much. These files will do it!
