### ISSUE TITLE
Crash on indexing

### ISSUE THREAD

**Issue by kiawizard** [xemle/home-gallery#72]
I have multiple directories added to home-gallery configuration, and all work well except one - when I add "2022", the app crashes on indexing. This could be connected to the increase of resolution of photos (up to 108MP) and change of format from JPG to HEIC. The output on crash:
```
index.readStream Reading file index from C:\Users\Vanya/.config/home-gallery/2022.idx

<--- Last few GCs --->

[41940:000002C38F969530]    56706 ms: Scavenge 614.2 (661.3) -> 614.2 (661.3) MB, 33.9 / 0.0 ms  (average mu = 0.992, current mu = 0.976) allocation failure
[41940:000002C38F969530]    58305 ms: Scavenge 806.2 (853.3) -> 806.2 (853.3) MB, 70.0 / 0.0 ms  (average mu = 0.992, current mu = 0.976) allocation failure
[41940:000002C38F969530]    61604 ms: Scavenge 1190.2 (1237.3) -> 1190.2 (1237.3) MB, 128.5 / 0.0 ms  (average mu = 0.992, current mu = 0.976) allocation failure


<--- JS stacktrace --->

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 00007FF7CC9BCD9F v8::internal::Isolate::ArchiveSpacePerThread+4927
 2: 00007FF7CC953846 SSL_get_quiet_shutdown+65206
 3: 00007FF7CC954746 node::OnFatalError+294
 4: 00007FF7CD254CCE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7CD23939D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF7CD0D23CC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF7CD0F969F v8::internal::Factory::NewUninitializedFixedArray+111
 8: 00007FF7CCFBC415 v8::debug::Script::GetIsolate+14533
 9: 00007FF7CCFA2E9D v8::internal::FeedbackNexus::ic_state+31229
10: 00007FF7CCF515EA v8::internal::JSObject::AddDataElement+1018
11: 00007FF7CCF0E27B v8::internal::StringSet::Add+1739
12: 00007FF7CCF26D1B v8::internal::Object::SetProperty+267
13: 00007FF7CCE01C25 v8::internal::Runtime::SetObjectProperty+373
14: 00007FF7CD060592 v8::internal::StubCache::Set+25954
15: 00007FF7CD2DBFDD v8::internal::SetupIsolateDelegate::SetupHeap+456749
16: 000002E1ED259FCA
cli.run error Error: 134 466197:26:48
```

**Comment by kiawizard** [comment]
After upgrading NodeJS from 15.8 to 19.7 the behavior changed: the output now contains hundreds of
```
extractor.image.heic error abort() at Error
    at jsStackTrace (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:1:15166)
    at stackTrace (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:1:15337)
    at Object.abort (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:18:7928)
    at _abort (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:1:216230)
    at QJ (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:5:186332)
    at yj (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:6:169467)
    at ok (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:10:12449)
    at om (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:10:78119)
    at nm (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:10:77923)
    at Array.ml (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:10:59099)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

The scan finished successfully, but no HEIC photos were added, only JPEG

**Comment by xemle** [comment]
Hi @kiawizard 

thank you for using HomeGallery and reporting your issue.

Can you confirm that index task works now from the first comment due the upgrade?

Can you identify on which image it crashes? The interactive mode has an `Debug extractor` in the system menu:

```
$ ./gallery.js 
? Gallery main menu … 
  Start server
  Update and process source files
▸ System
  Exit
? System options … 
  Show expanded configuration
▸ Debug extractor
  Rebuild database
  Back
```

This mode calls the extractor file by file and the logs will report the last working file. Maybe you can find out which file makes some troubles. Check the log file or increase the log level to `trace`.

Further the used npm module `heic-convert` uses `libheif-js` in 1.14.0. It got some updates up to 1.15.1, see release of [libheif](https://github.com/strukturag/libheif/releases). Maybe I can check with a problematic file of you if a new version of `libheif-js` will fix your issue.

**Comment by kiawizard** [comment]
Hi Sebastian!
First of all, thank you for sharing home-gallery, I think it is wonderful and closest to what I think a self-hosted web gallery should look like

Upgrading libheif-js to 1.15.1 indeed almost fixes the issue: now most of HEIC images are indexed ok, only some 108MP fail with
```
extractor.image.heic error abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 2046820352, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:1:15166)
    at stackTrace (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:1:15337)
    at abort (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:18:7928)
    at abortOnCannotGrowMemory (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:1:16402)
    at kO (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:11:7520)
    at zy (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:7:88384)
    at kM (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:5:192611)
    at lM (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:5:192707)
    at fl (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:10:34409)
    at el (c:\tools\home-gallery\node_modules\libheif-js\libheif\libheif.js:10:32849)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
extractor.image.rawPreview warn Raw image ce1bdbd:2022:220430 ╨б╤В╨░╤А╤Л╨╣ ╨│╨╛╤А╨╛╨┤ ╨Р╨╜╤В╨░╨╗╤М╤П ╨╕ ╨╜╨╛╤З╤М\20220430_171010.heic has no JPG sidecar nor a embedded preview image. Skip raw image
```
I'll attach such a picture to this comment in case you find it useful for testing
[20220430_171010.zip](https://github.com/xemle/home-gallery/files/10926201/20220430_171010.zip)

**Comment by xemle** [comment]
Hi @kiawizard 

> First of all, thank you for sharing home-gallery, I think it is wonderful and closest to what I think a self-hosted web gallery should look like

Thank you for the flowers.

Thank you so much also for the example image. As you said, I tried it with libheif-js 1.15.1 and it crashes :-( Do you have an idea how to proceed now with this issue?

I was able to open the file via Gimp 2.10.22 though...

**Comment by kiawizard** [comment]
Hi Sebastian!

Finally found a candidate for a solution to my issue :-)
For Windows I downloaded https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-4-Q8-x64-dll.exe from https://imagemagick.org/script/download.php (Q8 means 8-bit output, uses less memory than Q16)

npm install gm

```
const fs = require('fs')
const gm = require('gm').subClass({ imageMagick: '7+' });

var image = gm('kittens.heic');
image.resize(240, 240).write('kittens.jpg', function (err) {
  console.log(err);
});
```

**Comment by xemle** [comment]
Hi @kiawizard 

thank you for your positve response. So you are resizing the heic images via ImageMagick 7. That is great!

So heic conversion could be implemented as alternative for the buildin js solution - like the `useNative` extractor option for image resizing.

It seems you are familiar with code. PRs are welcome ;-)

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
